name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
    
    - name : Introduction
      uses: lowlighter/metrics@latest
      with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.introduction.svg
          user: N333kk
          base: header
          plugin_introduction: yes
          
    - name : Languages
      uses: lowlighter/metrics@latest
      with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.svg
          user: N333kk
          base: header
          plugin_languages: yes
          
